/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.gradle.api.tasks.bundling.Jar

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.20"

    id("java-library")
    id("maven-publish")
    signing
}

group = "com.serialIntCaster"
version = "1.1.0"

repositories {
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    testImplementation("org.testng:testng:7.6.1")
}
val sourcesJar by tasks.registering(Jar::class) {
    classifier = "sources"
    from(sourceSets.main.get().allSource)
}


publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "serial-int-caster"
            from(components["java"])
            versionMapping {
                usage("java-api") {
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime") {
                    fromResolutionResult()
                }
            }

            pom {
                name.set("Serial Int Caster")
                description.set("Encode or decode an integer to or from a string serial ")
                url.set("https://github.com/Kwaadpepper/serial-int-caster-kotlin")
                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://github.com/Kwaadpepper/serial-int-caster-kotlin/blob/main/LICENSE")
                    }
                }
                developers {
                    developer {
                        id.set("kwaadpepper")
                        name.set("Jérémy Munsch")
                        email.set("github@jeremydev.ovh")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com/serial-int-caster-kotlin")
                    url.set("https://github.com/Kwaadpepper/serial-int-caster-kotlin")
                }
            }
        }
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}
tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
            "Implementation-Version" to project.version))
    }
}

